### ISSUE TITLE
Can't update on EAP?

### ISSUE THREAD

**Issue by seanvree** [tidusjar/Ombi#1001]
#### Ombi Version:

Current Version: 2.0.1234 [EAP]

#### Update Branch:

EAP
#### Operating System:

Windows 10E 64

#### Mono Version (only if your not on windows)

N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):

http://pastebin.com/s8TyZmVa

```

#### Problem Description:

I switched from MASTER to EAP. Ran git checkout EAP, and changed the brand on the web-UI, however, I 'm getting an update notification, despite me running Git Pull from a CLI and it's saying I'm on the latest version.

Which branch includes the update support for Radarr?

#### Reproduction Steps:


C:\Ombi>git branch
* EAP
  master

C:\Ombi>git pull
Already up-to-date.

C:\Ombi>

**Comment by tidusjar** [comment]
Cloning the repo will only bring the source code down, because this is a .Net language it needs to be compiled into IL first. 
To get the actual compiled build you can click on the AppVeyor link in the readme: https://ci.appveyor.com/project/tidusjar/requestplex/branch/eap

and then click on Artifacts.
