### ISSUE TITLE
Sonarr "You must specify a Quality Profile."

### ISSUE THREAD

**Issue by porksandwich** [tidusjar/Ombi#1068]
#### Ombi Version:

V 2.1.1336 & 2.1.1382

#### Update Branch:

Stable & EAP

#### Operating System:

W 8.1

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

My TV requests do not show up, Ombi cannot connect to sonarr.  When I head to the sonarr settings, quality profiles & root folder are both blank.  If I try test connectivity, get root folders, get quality profiles I only get a message about selecting a quality profile.

![Error Message](https://cloud.githubusercontent.com/assets/16330854/22622988/37606f98-eb19-11e6-8be6-8ce9987bed98.png)

#### Reproduction Steps:

Upgrade DB from 2.0 to 2.1 (stable) or latest EAP, go to sonarr settings.

**Comment by SuperPotatoMen** [comment]
Can you hit the button  quality profiles first and after that use save.  Does that help?

**Comment by SuperPotatoMen** [comment]
You need to choose a quality profile otherway you get a error. Problem is now the system shows you the sonarr api respons instead of a Ombi error message.

**Comment by porksandwich** [comment]
> Can you hit the button quality profiles first and after that use save. Does that help?

Nope.  Hitting the "Get Quality Profiles" button gives me the same error.

**Comment by djxmind** [comment]
Hi There.  I too am having this issue all of a sudden. 

OS - Windows 10
Ombi Ver - Stable V2.1.0 (I reinstalled it twice and tried restarting)
Sonaar - Dev V2.0.0.4569

I had the service run perfectly up until i noticed this issue last night.  I am not sure if the latest Ombi stable is the reason or not because my Sonaar just updated to that version (maybe 15 minutes ago).

**Comment by djxmind** [comment]
Here is the error from the Log...

Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path '', line 1, position 1. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at Ombi.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 120 at Ombi.Api.SonarrApi.<>c__DisplayClass8_1.b__2() in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 137 at Polly.Policy.<>c__DisplayClass8_0`1.b__0() at Polly.RetrySyntax.<>c__DisplayClass14_0.b__1() at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory) at Polly.RetrySyntax.<>c__DisplayClass14_1.b__0(Action action, Context context) at Polly.Policy.Execute[TResult](Func`1 action, Context context) at Ombi.Api.SonarrApi.AddSeries(Int32 tvdbId, String title, Int32 qualityId, Boolean seasonFolders, String rootPath, Int32 seasonCount, Int32[] seasons, String apiKey, Uri baseUrl, Boolean monitor, Boolean searchForMissingEpisodes) in C:\projects\requestplex\Ombi.Api\SonarrApi.cs:line 137

**Comment by tidusjar** [comment]
Have you guys tried clearing your browser cache?

**Comment by djxmind** [comment]
I have tried that and several different browsers remotely. Get the same error every time.

**Comment by tidusjar** [comment]
Can you do me a favour, can you open the Developer Tools (F12) and then refresh the Sonarr Settings page.

There might be an error in the console in red (If the console doesn't appear press Esc):

Can you click the line number (far right) and send me a screenshot of that error:

e.g.
![image](https://cloud.githubusercontent.com/assets/6642220/22652599/f509d046-ec7e-11e6-8412-0b673521ec51.png)

**Comment by porksandwich** [comment]
![console](https://cloud.githubusercontent.com/assets/16330854/22662525/5f501a76-ec77-11e6-8ca3-3842c1086790.png)
![line number /w error](https://cloud.githubusercontent.com/assets/16330854/22662535/67646db6-ec77-11e6-8c02-7625c4c5095d.png)

Looks like its having an issue with the syntax of my previously selected rootFolder?

**Comment by porksandwich** [comment]
> Looks like its having an issue with the syntax of my previously selected rootFolder?

Yep.  Easy little fix.

@djxmind downgrade back to 2.0.1, go to your sonarr settings and remove the default root folder.  Hit save.  Shut down Ombi, copy your db back to 2.1, restart Ombi and everything should be functional.

**Comment by djxmind** [comment]
Thank you for the fix guys. I didn't have time to do the steps you wanted so I just deleted Ombi and started from scratch with the dev branch
