### ISSUE TITLE
start command not working for windows install instructions

### ISSUE THREAD

**Issue by ucantcme69** [tidusjar/Ombi#1078]
#### Ombi Version:

V 2.1.0

#### Update Branch:

Stable

#### Operating System:

Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Following the windows instructions and running: nssm start Ombi results in the following:

Set parameter 'Start' for service 'ombi' Enviroment variable parameter 'Start' for service 'Ombi" not defined

#### Reproduction Steps:

Everything else in the installation guide worked as expected. I do have a previous version of plex requests installed I believe. Would it be helpful to remove that or would that have no impact on the issue at hand?

**Comment by SuperPotatoMen** [comment]
Pleas ask this question on the how to website: http://www.htpcguides.com/install-plex-requests-net-windows-system-service/

**Comment by CBers** [comment]
I know the ISSUE is closed, but thought I'd post.

@ucantcme69 - I only recently followed that guide on Windows 7 and it worked fine.

Did you run the "Set the home directory for the Ombi PlexRequests folder to the installation directory" ??

nssm set Ombi AppDirectory "C:\<Ombi-path>"

On Windows 10, you have to UNBLOCK the zip file - did you do that ??

**Comment by ucantcme69** [comment]
Yes I did both of those instructed in the guide

**Comment by SuperPotatoMen** [comment]
Hi Guys, we only support the option to manually start the ombi.exe file. 
Support to auto start it on the how to website. I'm sorry but we can't help you on this one :(
