### ISSUE TITLE
Ombi Crashes Frequently

### ISSUE THREAD

**Issue by Kolmain** [tidusjar/Ombi#1171]
#### Ombi Version:

V 2.1.0

#### Update Branch:

Stable/Early Access

#### Media Sever:

Plex

#### Media Server Version:

Latest plexpass.

#### Operating System:

Ubuntu 16

#### Mono Version (only if your not on windows)

4.6.2

#### Applicable Logs (from `/logs/` directory or the Admin page):
There are only these in the logs, and there are ALOT Of them. Here is a snippet.
```

2017/02/22 06:06:13.303 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Salt Directors Cut is null
2017/02/22 06:06:13.309 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Saving Mr Banks is null
2017/02/22 06:06:13.312 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Saving Private Ryan is null
2017/02/22 06:06:13.316 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Scooby Doo is null
2017/02/22 06:06:13.319 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Scooby Doo! Curse of the Lake Monster is null
2017/02/22 06:06:13.323 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Scooby Doo! The Mystery Begins is null
2017/02/22 06:06:13.327 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Scrooged is null
2017/02/22 06:06:13.331 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Secret in Their Eyes, The is null
2017/02/22 06:06:13.335 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Secret Life of Walter Mitty, The is null
2017/02/22 06:06:13.340 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Separation, A is null
2017/02/22 06:06:13.344 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Seventh Son is null
2017/02/22 06:06:13.349 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Sherlock Holmes is null

```

#### Problem Description:

Ombi frequently crashes and must be reset manually.

#### Reproduction Steps:

Unsure.

**Comment by SuperPotatoMen** [comment]
The logs you posted here doesn't tell why it is crashing :(

Can you set your log level to debug and post the logs when it crashed?

**Comment by Kolmain** [comment]
@SuperPotatoMen I set the log from `INFO` to `DEBUG`. I'll let you know when it crashes again!

**Comment by tidusjar** [comment]
Plex Episode searching enabled?

**Comment by Kolmain** [comment]
@tidusjar Advanced Search enabled, Episode Search disabled.

**Comment by Kolmain** [comment]
@SuperPotatoMen @tidusjar Crashed again on `DEBUG`, this is all I have leading up to the crash:
```
Provider Id on movie The Connection is null	Ombi.Services.Jobs.PlexContentCacher	Error	2/23/2017 8:05:58 AM
Provider Id on movie Big Short, The is null	Ombi.Services.Jobs.PlexContentCacher	Error	2/23/2017 8:05:58 AM
Provider Id on movie Anchorman the Legend of Ron Burgundy is null	Ombi.Services.Jobs.PlexContentCacher	Error	2/23/2017 8:05:58 AM
```

**Comment by Kolmain** [comment]
This is the only non-PLexContentCacher error in the log:
`Requests that will be updated count 0	Ombi.Services.Jobs.PlexAvailabilityChecker	Debug	2/23/2017 6:10:36 AM`

**Comment by Kolmain** [comment]
Another crash, same thing- only loads of the PlexContentCacher errors...

**Comment by mushbuddygoose** [comment]
I had a similar error which I fixed the old fashioned way -- just deleted my install excepct the sqlite file, redownloaded, and moved over all the files. That seems to have fixed it for now. Been 1 week and no issues.

**Comment by jneljeff** [comment]
I have the opposite advice.  If your sqlite file was imported from a previous build Ombi can become unstable.  Rename it to Ombi.sqlite.bak and reboot Ombi.  This will generate a fresh database you can configure from scratch and see how it runs.  If its just as unstable, you can restore your old file.

**Comment by AmansRevenger** [comment]
Or use this script on Linux I wrote for myself:

`#!/bin/bash

echo "PlexRequestCheck läuft"
date
touch /var/skript.txt

var1=$(netstat -tulpn |grep :3000)

echo $var1


if [ -n $var1 ]

then
       echo "Ombi is not running "
 sudo mono /opt/plexrequests/Ombi.exe
       echo "Ombi has been restarted"

else
       echo "Ombi is running!

fi
`

works fine for me and fixes the 3-4 crashes in a week...

**Comment by SprkFade** [comment]
I've got the same error as the others in the thread.  Here's the error right when it crashes:

`2017/02/26 22:12:55.553 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie 400 Days is null 
2017/02/26 22:12:55.599 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie The Autopsy of Jane Doe is null 
2017/02/26 22:12:55.615 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Best in Show is null 
2017/02/26 22:12:55.638 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Brothers is null 
2017/02/26 22:12:55.647 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Chinatown is null 
2017/02/26 22:12:55.671 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Denial is null 
2017/02/26 22:12:55.689 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Dune is null 
2017/02/26 22:12:55.691 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie The Edge of Seventeen is null 
2017/02/26 22:12:55.711 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Friday Night Lights is null 
2017/02/26 22:12:55.761 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie The Hitchhiker's Guide to the Galaxy is null 
2017/02/26 22:12:55.777 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Ice Age: Collision Course is null 
2017/02/26 22:12:55.808 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie The Last Samurai is null 
2017/02/26 22:12:55.855 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Mr. & Mrs. Smith is null 
2017/02/26 22:12:55.969 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Space Cowboys is null 
2017/02/26 22:12:55.987 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Storks is null 
2017/02/26 22:12:56.030 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie The Visit is null 
2017/02/26 22:12:56.038 Ombi.Services.Jobs.PlexContentCacher Error: Provider Id on movie Warrior is null 
2017/02/26 22:12:56.356 Ombi.Services.Jobs.PlexContentCacher Error: Failed to obtain Plex libraries Mono.Data.Sqlite.SqliteException: Abort due to constraint violation
NOT NULL constraint failed: PlexContent.ItemID
  at Mono.Data.Sqlite.SQLite3.Reset (Mono.Data.Sqlite.SqliteStatement stmt) <0x41d07c60 + 0x00233> in <filename unknown>:0 
  at Mono.Data.Sqlite.SQLite3.Step (Mono.Data.Sqlite.SqliteStatement stmt) <0x41d07840 + 0x0012a> in <filename unknown>:0 
  at Mono.Data.Sqlite.SqliteDataReader.NextResult () <0x41d05860 + 0x00513> in <filename unknown>:0 
  at Mono.Data.Sqlite.SqliteDataReader..ctor (Mono.Data.Sqlite.SqliteCommand cmd, CommandBehavior behave) <0x41d05610 + 0x0013a> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) Mono.Data.Sqlite.SqliteDataReader:.ctor (Mono.Data.Sqlite.SqliteCommand,System.Data.CommandBehavior)
  at Mono.Data.Sqlite.SqliteCommand.ExecuteReader (CommandBehavior behavior) <0x41cf4a90 + 0x0003b> in <filename unknown>:0 
  at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader (CommandBehavior behavior) <0x41d34e90 + 0x00013> in <filename unknown>:0 
  at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader (CommandBehavior behavior) <0x41d34e60 + 0x00018> in <filename unknown>:0 
  at Dapper.SqlMapper.QueryMultipleImpl (IDbConnection cnn, Dapper.CommandDefinition& command) <0x41938580 + 0x00212> in <filename unknown>:0 `

**Comment by SuperPotatoMen** [comment]
Guys can you upgrade to the last EAP version, Jamie make some changes. I was wondering if it fixed some problems for you

**Comment by SuperPotatoMen** [comment]
Problem for now is, we have some issues with mono that make the app unstable.
@tidusjar is going to re-write it to .net port but that will take a LOT of time.
I will close this for now.

You can follow the progress over here: https://github.com/tidusjar/Ombi/issues/865
