### ISSUE TITLE
Newsletter date range.

### ISSUE THREAD

**Issue by elit3ge** [tidusjar/Ombi#1182]
#### Ombi Version:

V 2.1.1442

#### Update Branch:

Early Access Preview

#### Media Sever:

Plex

#### Media Server Version:

V1.3.4

#### Operating System:

Docker

#### Mono Version (only if your not on windows)

4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)

#### Problem Description:

Not sure if it is a bug. Depending on the outcome. What is the date range for the newsletter. I have sent out a test newsletter and I know for a fact that some of the movies that it is showing are more than 4 weeks old but still appearing in the newsletter. What is the date range we are looking at?

#### Reproduction Steps:

Add some movies, give it a couple of weeks and see if they appear in the newsletter still.

**Comment by tidusjar** [comment]
It's not using a date range currently.

Basically for Plex we just call the `recentlyAdded` API endpoint and just use everything in that.

Now going forward I will be doing what I have done for Emby, since I keep a local cache of the data in Plex locally, I can use that data to see what has been added so we do not show duplicates.
