### ISSUE TITLE
Unable to start as service with latest Windows 10 Creators Update

### ISSUE THREAD

**Issue by arm3n** [tidusjar/Ombi#1322]
I have been running fine with v2.1.0 and its nssm-created service, but every since I upgraded to Windows 10 Creators Update, the service is now getting paused and won't resume.  I have tried re-installing with the latest 2.2 version to no avail.

**Comment by vincemarsters** [comment]
This is not a bug in Ombi but a problem between NSSM and Win10 Creators Update. I had this (most of my nssm services seemed to be stuck in a paused state. The fix was simple. From an administrative command prompt run 'nssm set <servicename> appnoconsole 1'. In my case I use ombi as the service name so I ran 'nssm set obmi appnoconsole 1'.

**Comment by arm3n** [comment]
Thanks a lot Vince, that did the trick!
