### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1457]
- Rework the TV Requests page
    - This still need a lot of work, mainly around how we will visually display how to approve "child" requests, I was thinking about when we display the TV requests there should be a single button "Manage" that then takes to a new page listing all child requests where we can then, approve, decline, delete etc.

**Comment by tidusjar** [comment]
Anyone have any idea (UI design wise) how this could look?

**Comment by dhruvb14** [comment]
Working on this now, have it partially working but can't get tvshowrequestbuilder.cs to stop throwing exception. Once fixed all that is left is CSS, however with this new bug I can't test CSS till C# code is fixed

Video: https://1drv.ms/v/s!AutEqhj08rK0hPZdfbCuyFTiCPaigA
If you want to help, here is the code github.com/dhruvb14/ombi

Once fixed ill create a PR

**Comment by dhruvb14** [comment]
Progress So far: https://1drv.ms/v/s!AutEqhj08rK0hPZhpM_dxR630bdKuA
#1488

**Comment by tidusjar** [comment]
Looks great!

**Comment by tidusjar** [comment]
@dhruvb14 is the `tvrequests-manage` component needed anymore?

**Comment by dhruvb14** [comment]
@tidusjar I want to leave it for now since I plan on embedding that component as a partial view into the main screen to clean up code. Just had not gotten around to it in initial PR. Code in that file and the new view I created is almost 1:1 so it would be great code-reuse/maintainability feature to leave.

**Comment by tidusjar** [comment]
@dhruvb14 Is there any point me hooking up all the buttons and sorting that out yet?

**Comment by dhruvb14** [comment]
If you do, make sure you pass around objects in the functions as it makes its 2x easier to move functions around. (ng-click="addChildren(children)" instead of ng-click="addChildren()") Don't use any stored variable on the component from inside any functions you call as the new view has multiple children visible. I plan on trying to clean up code this weekend also so maybe I can make use of that old manage view by embedding it into the new UI so it's easier to maintain.

**Comment by tidusjar** [comment]
Yeah that makes sense, I'm planning to work on the scheduled jobs, so things appear as available.

**Comment by dhruvb14** [comment]
#1496
