### ISSUE TITLE
Episode Select

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1463]
This page works but is very ugly and basic

Maybe on the TV search we need a "Request" button that will take us to this page and the current dropdown options (Request All, First Season, Latest season) should be on this page somewhere?

We need to make it more obvious how to request things using this page.

**Comment by dhruvb14** [comment]
You can tag me. Its completed but I can help maintain issues as they come up...

**Comment by PotatoQuality** [comment]
@tidusjar Can you Tag @dhruvb14 for this one?

**Comment by tidusjar** [comment]
Can't tag if not an official contributor to the project

**Comment by tidusjar** [comment]
@dhruvb14 Looks like the search dropdown is no longer working for Tv Shows e.g. on the search page, far right in the search bar select Popular Shows

**Comment by tidusjar** [comment]
Also the styling has gone back to blue @dhruvb14 not sure why :'(

**Comment by dhruvb14** [comment]
Maybe encapsulation got enabled. As for popular shows not sure what would cause the issue as I left that as is. I'll look at it tonight.

**Comment by dhruvb14** [comment]
Hey @tidusjar I was unable to find the issue with the Styling as when I forked and built UI was working as expected. I did however figure out the main issue with the dropdown and they are all working with the one issue of the update method which is called afterward which puts in the TV Poster image. I have fixed the broken update method but it does not look like PrimeNG's treetable is detecting when I make changes to the variable and UI stays incorrect... Any help? I update the interfaces so you can make sense of what I was doing since I was lazy on first PR and just allowed any's.

github.com/dhruvb14/ombi

**Comment by tidusjar** [comment]
By the sounds of it we need to map the getinfo response to the new interface, using a new interface instead of any makes more sense. 

So no idea why the CSS isn't working? Hmmm strange

**Comment by dhruvb14** [comment]
I plan on working on it this weekend. I really want to modify the rest endpoint to return a VM instead of the model so that I don't have to modify the data clientside like I am right now with the transformData() method.

**Comment by tidusjar** [comment]
That makes sense!
