### ISSUE TITLE
Environment variable parameter "AppDirectory" for service "Ombi" not defined

### ISSUE THREAD

**Issue by Dankasaurus6** [tidusjar/Ombi#1485]
Anybody else having this issue during install?
![image](https://user-images.githubusercontent.com/14925468/29148961-4f8e43b0-7d36-11e7-8838-92334bb8ea2a.png)

!! Version 2.X is not supported anymore. Pleas don't open a issue for the 2.x version.
See https://github.com/tidusjar/Ombi/issues/1455 for more information.

#### Ombi Version:

V 3.XX.XX

#### Update Branch:

Stable/Early Access Preview/development

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Mono Version (only if your not on windows)

(Place text here)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ``` tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

(Place text here)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Errr... What is the actual issue because I don't see one.

**Comment by Dankasaurus6** [comment]
Why did you close this? It is telling me the parameter is not defined when I try to define it, look at the picture.

**Comment by tidusjar** [comment]
I closed it as whatever you are trying to do is not related to Ombi. Looks like you are trying to do something with NSSM

**Comment by PotatoQuality** [comment]
Naam is not a program that we created. We can't support software that is not form us...

**Comment by Dankasaurus6** [comment]
It's necessary for Ombi to work though... It's part of the instructions for installation for Ombi.

**Comment by Dankasaurus6** [comment]
Whatever, I'll just not bother with Ombi all together then. Cool concept, bad execution, zero support.

**Comment by PotatoQuality** [comment]
Ehhh.. Its free software?

**Comment by PotatoQuality** [comment]
Pleas explain to me how we can support software that Isn't from us?

**Comment by Dankasaurus6** [comment]
Please explain why nssm is necessary for Ombi yet you fail to help when it doesn't work. I know it's free, and I sure as hell wouldn't donate to you after this. You wouldn't even leave my issue open for others to come in and help, maybe they've had this issue in the past. Instead you just closed the issue. Instead of attempting to help, you double down on explaining how it isn't your problem.

**Comment by tidusjar** [comment]
Please read this:
https://github.com/tidusjar/Ombi/issues/1455

Also did you read the template for the issue you opened?

NSSM is not necessary for Ombi. You can run Ombi by directly running the .exe,

I'm not a NSSM expert so I cannot help you with this issue.

**Comment by PotatoQuality** [comment]
First of all. Pleas read the issue format file before you start your flame war to people that using the free time to support open and free software. 

When you open a issue. It started with the text:

!! Version 2.X is not supported anymore. Pleas don't open a issue for the 2.x version.
See #1455 for more information.

I guess you didn't read it at all...

2. Nssm Isn't necessary you can start Ombi with opening Ombi.exe with administrator rights. 

3. you didn't follow the instructions. You are missing the "   " tags.  So instead of flaming on zero support, start follow the instructions...

**Comment by Dankasaurus6** [comment]
I followed your instructions and they don't work, thanks for all the support.

**Comment by PotatoQuality** [comment]
You need to run nssm set Ombi AppDirectory "D:\Ombi"

**Comment by rickey527** [comment]
I agree with you Dankasaurus6. Awesome idea and really grateful these guys do this in their free time. However, if you are going to have an install guide you should be willing to offer support, not condescending comments, when it doesn't work. And for me, I get the same error as you are getting. I read that post 1455. Didn't answer a single thing or even reference this error at all. Best of luck guys but you've left me with a bad taste for your program because of the way you talk to someone just trying to get some help.

**Comment by PotatoQuality** [comment]
@rickey527 pleas read the full topic.
 Version 2.0 is not supported anymore.  If you read #1455 you will understand why we not supporting V2

**Comment by PotatoQuality** [comment]
Also, we cant support the program nssm. Its not a program that we wrote and not necessary to run Ombi.
You can just run ombi.exe and that will do the job.

**Comment by rickey527** [comment]
Easy solution. Temporarily take down the install guide. I followed it to the letter and ended up with an error. If it doesn't apply because of a newer version being developed then you should probably just remove it until it does apply. Otherwise, it's just confusing and misleading. Thanks for your response.

**Comment by PotatoQuality** [comment]
Well, the problem you have is a error with nssm and windows. Somethimes it is helping do al over again.
Nothing change but is for some reason working.

We can't take it down at this moment Version 2.1 is working and we like to give you guys a chance to use it.
Version 3 is not ready yet to mark it for "stable". We will rewrite the install guide.

**Comment by Dankasaurus6** [comment]
Nice to see there is still no help here. Sorry Rickey we are on our own

**Comment by PotatoQuality** [comment]
@Dankasaurus6 you still don't get our point?

**Comment by Dankasaurus6** [comment]
Did you ever get mine? Don't bother responding

**Comment by PotatoQuality** [comment]
@Dankasaurus6 I get you point. But the problem is. You are tilted on a program that is not writing by us and NSSM is **not necessary** for Ombi.
But you just ignore that point.

**Comment by PotatoQuality** [comment]
We state pretty clearly that we aren't doing support as working on V3 of Ombi, and would rather get that done sooner than delay it by trying to support any current issues on the old code. It's literally 2 guys doing the best they can in the limited spare time they have.

So just stop be tilted and try out V3 when its ready.

**Comment by PotatoQuality** [comment]
@rickey527 Version V3 is now in open beta.
