### ISSUE TITLE
Sonarr/Radarr root folders and quality

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/Ombi#1517]
We need to add the Root folders & quality selection on the requests page back in.

- [x] Sonarr Root Folders
- [x] Sonarr Quality
- [x] Radarr Root Folders
- [x] Radarr Quality

**Comment by PotatoQuality** [comment]
For Radarr it also needed to provide the Available parameter. can we include that also?

**Comment by tidusjar** [comment]
What's that?

**Comment by weirdcrap** [comment]
@tidusjar I believe PotatoQuality is referring to this: https://github.com/Radarr/Radarr/wiki/Minimum-Availability

**Comment by tidusjar** [comment]
Ah ok, we already have that in the settings?

**Comment by weirdcrap** [comment]
Not in V2, I haven't tried V3 yet.

Currently in V2 that particular field is just blank when movies requested through Ombi are viewed in Radarr: 
![image](https://user-images.githubusercontent.com/22824785/30922686-76589c2a-a36f-11e7-95f3-d8281ef91bc9.png)

The movie is still searched for and downloaded even without an availability setting.

**Comment by PotatoQuality** [comment]
@weirdcrap  correct. They have a default setting. If the api doesn't send something the minimum availability then they have a fallback setting for it.

**Comment by Celedhrim** [comment]
Hi ,

Providing default tag will be great too , I use tag to choose with or without subtitle .

Maybe a default tag when added from ombi

**Comment by mattohm** [comment]
It would also be nice if users with auto approve permissions could set the root folders when making the request.

**Comment by PotatoQuality** [comment]
Guys, pleas don't do feature request. We focussing now only on the basic features.

You can open a feature request over here: https://feathub.com/tidusjar/Ombi

**Comment by PotatoQuality** [comment]
@tidusjar Why is the Sonarr Root Folders not checkt? I see in your last code push code for sonarr and not for radarr?

**Comment by tidusjar** [comment]
I did Radarr today :)

**Comment by kyse** [comment]
Would be nice to have the ability to set individual users to use a specific default location.  One of my biggest problems right now and one of my biggest reasons to write my own app before I found this app.

**Comment by tidusjar** [comment]
So, you scope your downloads to user folders?

**Comment by kyse** [comment]
For example, I have a main library for series most all users want to see on deck and recently added, etc within Plex.  And there are certain series that only the woman watches I'd rather not see, thus I throw her stuff on Sonarr under a separate library.  Being able to use this app to expose the request feature to her without her yelling at me to do it myself would be great, but so far there's' no way to restrict her to using her library folder, she's not very tech savy, so teaching her the quirks of Sonarr is not ideal.  Being able to set a default folder path for her requested shows + a bonus add tags so I can ensure Sonarr doesn't only look for obfuscated uploads since her shows aren't as popular and therefore aren't always available in obfuscated forms would be amazing.

**Comment by tidusjar** [comment]
Moved into develop branch

**Comment by kyse** [comment]
Took a look at the updates, nice addition to be able to select the root folder per request approval.

But if I had a user I'd rather allow to auto approve requests but have his/her requests going to a different root folder, this doesn't cover such a scenario.  It will still default to the sonarr/radarr setting page's root folder.  Would be nice to be able to set per user per automator (sonarr & radarr) the root folder.  That way when they submit a request and it auto approves, I get the desired affect.

**Comment by tidusjar** [comment]
I have already got plans for this. I will introduce a new role that will allow used to select their own folders if they have that role

**Comment by kyse** [comment]
Nice!

A thought on that though, users might not understand the difference between the Plex library and the root folder.  Combine that with the fact you can have multiple "paths" to a single Plex library, could be complicated for the less computer literate folks.  Please consider allowing the admin to limit a user to a different specified root folder rather than the default specified on the sonarr/radarr settings page as well.
