### ISSUE TITLE
Can not expand/use 'View' button on TV Show seasons with latest version of Firefox

### ISSUE THREAD

**Issue by Scorcher7986** [tidusjar/Ombi#1544]
Unsure if this issue is a problem with Ombi's implementation or a new bug in Firefox.

In the latest version of Firefox (56.0, released September 28, 2017), you are unable to click the 'View' button next to TV Show requests - nothing happens. Additionally, when trying requesting a new TV Show, attempting to use the 'Select' button for the seasons doesn't do anything.

This bug is not present in Chrome and also was not present in the previous version of Firefox.

No error is thrown by the Ombi application - only in the browser console. Here's the error if it helps:
```
TypeError: e is undefined
Stack trace:
l</e.prototype.openClosestTab@https://{redacted}/ombi/dist/main.js?v=OxoE88ycsIg5OizDMDyTZXVCcyB3x6KEy6GLcO3dB08:48:148920
View_e_3/<@ng:///e/e.ngfactory.js:46:23
Qn/<.handleEvent@https://{redacted}/ombi/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:113:1580
handleEvent@https://{redacted}/ombi/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:113:8808
ie@https://{redacted}/ombi/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:64:1741
Me/<@https://{redacted}/ombi/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:71:2363
g/<@https://{redacted}/ombi/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:620:545
vendor_ca6a7d745ecdb0207d63</</</</u</t.prototype.invokeTask@https://{redacted}/ombi/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:986:8040
onInvokeTask@https://{redacted}/ombi/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:36:815
vendor_ca6a7d745ecdb0207d63</</</</u</t.prototype.invokeTask@https://{redacted}/ombi/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:986:7953
vendor_ca6a7d745ecdb0207d63</</</</l</r.prototype.runTask@https://{redacted}/ombi/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:986:3208
vendor_ca6a7d745ecdb0207d63</</</</p</e.invokeTask@https://{redacted}/ombi/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:986:9178
h@https://{redacted}/ombi/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:951:3306
f@https://{redacted}/ombi/dist/vendor.js?v=pUA804ySrmGzIBRTYpb-fu7BcduINiiOr4kFIymZPGA:951:3526
  vendor.js:8:349
```

**Comment by Scorcher7986** [comment]
Note:
Seems like this affects all firefox based web browsers, whilst chromium based works fine (according to @Sm0k3d0uT)
> Doesn't work with:
> Cyberfox 52.3.0
> Firefox Nightly 58.0a1
> Waterfox 55.2.0
>
> Does work with:
> Vivaldi 1.12
> Chrome 61.0.3163.100

**Comment by Scorcher7986** [comment]
Just did a bit of research into what might have caused the bug with the new version of Firefox. Not sure if it's the same issue but I found [this](https://support.mozilla.org/en-US/questions/1178939) if it helps.

**Comment by Zaaaaac** [comment]
The problem is still there :/

`ERROR TypeError: e is undefined
Trace de la pile :
d</e.prototype.openClosestTab@http://localhost/ombi/dist/main.js?v=R9gwFMgG-LpJrIup_EexmEmU0D70Fiajf_mfjR773R0:50:140524
View_e_13/<@ng:///e/e.ngfactory.js:133:27
handleEvent@http://localhost/ombi/dist/vendor.js?v=QYfPzEwhF5FNwzKai1Tgx1-QdsiTjiBLe_3Tmly-Li4:113:1473
handleEvent@http://localhost/ombi/dist/vendor.js?v=QYfPzEwhF5FNwzKai1Tgx1-QdsiTjiBLe_3Tmly-Li4:113:8809
re@http://localhost/ombi/dist/vendor.js?v=QYfPzEwhF5FNwzKai1Tgx1-QdsiTjiBLe_3Tmly-Li4:64:1745
Pe/<@http://localhost/ombi/dist/vendor.js?v=QYfPzEwhF5FNwzKai1Tgx1-QdsiTjiBLe_3Tmly-Li4:71:2404
y/<@http://localhost/ombi/dist/vendor.js?v=QYfPzEwhF5FNwzKai1Tgx1-QdsiTjiBLe_3Tmly-Li4:565:545
vendor_70719b4393a68c63f527</</</</p</t.prototype.invokeTask@http://localhost/ombi/dist/vendor.js?v=QYfPzEwhF5FNwzKai1Tgx1-QdsiTjiBLe_3Tmly-Li4:1083:8054
onInvokeTask@http://localhost/ombi/dist/vendor.js?v=QYfPzEwhF5FNwzKai1Tgx1-QdsiTjiBLe_3Tmly-Li4:36:815
vendor_70719b4393a68c63f527</</</</p</t.prototype.invokeTask@http://localhost/ombi/dist/vendor.js?v=QYfPzEwhF5FNwzKai1Tgx1-QdsiTjiBLe_3Tmly-Li4:1083:7967
vendor_70719b4393a68c63f527</</</</u</i.prototype.runTask@http://localhost/ombi/dist/vendor.js?v=QYfPzEwhF5FNwzKai1Tgx1-QdsiTjiBLe_3Tmly-Li4:1083:3220
vendor_70719b4393a68c63f527</</</</d</e.invokeTask@http://localhost/ombi/dist/vendor.js?v=QYfPzEwhF5FNwzKai1Tgx1-QdsiTjiBLe_3Tmly-Li4:1083:9192
h@http://localhost/ombi/dist/vendor.js?v=QYfPzEwhF5FNwzKai1Tgx1-QdsiTjiBLe_3Tmly-Li4:1055:3376
f@http://localhost/ombi/dist/vendor.js?v=QYfPzEwhF5FNwzKai1Tgx1-QdsiTjiBLe_3Tmly-Li4:1055:3623
  vendor.js:8:349
	_ http://localhost/ombi/dist/vendor.js:8:349
	vendor_70719b4393a68c63f527</</_o</t.prototype.handleError http://localhost/ombi/dist/vendor.js:155:242
	Pe/< http://localhost/ombi/dist/vendor.js:71:2425
	y/< http://localhost/ombi/dist/vendor.js:565:545
	vendor_70719b4393a68c63f527</</</</p</t.prototype.invokeTask http://localhost/ombi/dist/vendor.js:1083:8054
	onInvokeTask http://localhost/ombi/dist/vendor.js:36:815
	vendor_70719b4393a68c63f527</</</</p</t.prototype.invokeTask http://localhost/ombi/dist/vendor.js:1083:7967
	vendor_70719b4393a68c63f527</</</</u</i.prototype.runTask http://localhost/ombi/dist/vendor.js:1083:3220
	vendor_70719b4393a68c63f527</</</</d</e.invokeTask http://localhost/ombi/dist/vendor.js:1083:9192
	h http://localhost/ombi/dist/vendor.js:1055:3376
	f http://localhost/ombi/dist/vendor.js:1055:3623`
