### ISSUE TITLE
Poster Paths issue persists 

### ISSUE THREAD

**Issue by causefx** [tidusjar/Ombi#1618]
Same issue as #1533 

I wrote a checker in the api function for Org but it seems the issue is still there.  Posters sorted by date for convenience.  

![image](https://user-images.githubusercontent.com/16184466/31954774-5732d770-b89b-11e7-8a07-b29ca391338d.png)

**Comment by tidusjar** [comment]
Any idea how to recreate it? I cannot work out in code where it could potentially be doing this.

**Comment by tidusjar** [comment]
I think I found it, when we send a notification we edit the database entity for movies to add the full url (since emails for example need the full url to render the image), but it seems that the entity was still being tracked by EntityFramework so the next time we called `SaveChangesAsync()` it was picking up that modified tracked entity and saving it. 

So I just committed a change that will fix this now!

**Comment by causefx** [comment]
sweet!  good catch mate!

**Comment by tidusjar** [comment]
Let me know if it's all good, it won't fix currently what's in your database, but should stop it in the future from happening.

**Comment by causefx** [comment]
I already coded in checks to fix bad entries in org :)
