### ISSUE TITLE
Sonarr marks all seasons as monitored after requesting "first season"

### ISSUE THREAD

**Issue by justinpeterson13** [tidusjar/Ombi#1652]
#### Ombi build Version:

V 3.0.2255

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Microsoft Windows 10.0.16299

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2017-10-31 10:40:49.717 -04:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized
2017-10-31 10:42:00.941 -04:00 [Error] StatusCode: BadRequest, Reason: Bad Request
2017-10-31 10:42:01.210 -04:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-10-31 10:42:01.633 -04:00 [Error] StatusCode: BadRequest, Reason: Bad Request
2017-10-31 10:42:01.661 -04:00 [Error] StatusCode: BadRequest, Reason: Bad Request
2017-10-31 10:42:01.884 -04:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-10-31 10:42:01.907 -04:00 [Error] StatusCode: NotFound, Reason: Not Found


```

#### Problem Description:

Sonarr attempted to download all seasons of a show after just the first was requested. Not sure if the logs reflect that or not...

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by wikkixwikki** [comment]
Version 3.0.2853
OS Description Linux 4.15.0-1-MANJARO
Server: Emby
Clients: Sonarr
Example - TV Show1 has 10 seasons. I have all of Seasons 9 and all of currently available 10 as it is actively running, but no other seasons. When searching for TV Show1, I'm able to use the drop down to request specific episodes, but at that point, every episode is marked available rendering the requests useless. Even future unaired episodes.

Example 2 - Same scenario, but slightly different results. TV Show2 has 3 seasons. I have only season 3 in its entirety. From the initial search results screen, it is marked as available and I cannot interact with the drop down menu to requests seasons or individual episodes. It's completely locked out telling me it's available when it isn't.

It's done this since I first attempted to use it a few weeks ago. I've just been updating and checking every once in a while to see if it's sorted, but now I figured I'd see if anyone has had this issue or if I'm doing something obviously wrong. Sonarr's cousin, Radarr, works perfectly fine. The logs are pretty empty. just some search results. The only error is fanart.tv not finding something. I'm happy to provide any other info upon request.


https://www.reddit.com/r/Ombi/comments/7vj9q6/v3_if_one_episode_is_available_all_show_as/

**Comment by softworkz** [comment]
@wikkixwikki I got the same problem, but I think you should create a new issue for this

**Comment by softworkz** [comment]
About the original issue: I cannot confirm the described behaviour with the latest versions of ombi and Sonarr. Here, requesting "First Season" does not set other seasons as monitored.

**Comment by thegame3202** [comment]
Also having this issue.  I noticed that if the show already exists, and you're requesting additional season, that works great. Requesting first season adds all as monitored in Sonarr.

**Comment by anojht** [comment]
Can someone here please update to the latest develop and let me know if you have the same issue? I believe my fix for #1745 might have fixed this as well. Thanks!

**Comment by anojht** [comment]
Closing this for lack of response, reopen if issues exists.

**Comment by SturmB** [comment]
I'm afraid I'm having this issue now.

**Ombi version:** 3.0.4659

One of my users ran into this recently. She requested only the first season of Code Black to see whether or not she liked it. After she watched it, she then went back to Ombi to request the other two seasons. However, Ombi would not let her do so, giving her a screen similar to this:
![image](https://user-images.githubusercontent.com/6216224/61236970-52f66580-a707-11e9-8aa0-701dc5d3ace4.png)

It looks like Ombi had requested seasons 2 and 3, but Sonarr did not download them. It definitely marked them as monitored, but did not do the "Search for monitored episodes" action on those seasons. So I don't know why Ombi told Sonarr to monitor the episodes at all, let alone doing so without searching for them, which has now put Ombi in a state of "Processing" for those episodes. Thus, my user was unable to request them because Ombi thought they were _already_ requested.
