### ISSUE TITLE
Specify Category when Approving Movies (CouchPotato)

### ISSUE THREAD

**Issue by evilspectre** [tidusjar/Ombi#176]
Similar to #170, but with approving Movies. CP lets you select a Category when adding a Movie, would just need to pull all Categories and list in a drop down so it can be selected before approving the Movie.

**Comment by onedr0p** [comment]
I laid out a spec in #170 that I hope would be the end game for these advanced settings.

**Comment by armandkd** [comment]
Hi,
Was this ever released? This functionality would be really great!
Thanks.

**Comment by onedr0p** [comment]
Come join us on Radarr, CouchPotato is dead (to me).

**Comment by armandkd** [comment]
Ok, I switched to Radarr and disabled Couchpotato. Still no way of selecting a profile when requesting a movie as an admin...

**Comment by onedr0p** [comment]
Why are you requesting a movie as admin? Sure you can just use Radarr... lol

I'd make a feature request here for Ombi to support what you want with Radarr.

**Comment by armandkd** [comment]
I am requesting as an admin because I use Plex SSO and doesn't want to disconnect/reconnect every time I want to request/approve a movie.
I am not using Radarr directly because I like to have the least amount possible of services exposed to the web (even behind a reverse proxy). Moreover, the functionalities of Radarr go far beyond just requesting movie so it's overkill to use it only for that, and it would be best if I can have the same user experience as my users when requesting a movie.
I just don't see why a functionality available when users are requesting movies wouldn't be available to admins.
I will create a feature request, thank you for your help.
