### ISSUE TITLE
Hide Password Field on Login Page

### ISSUE THREAD

**Issue by basmith7** [tidusjar/Ombi#1815]
#### Ombi build Version:

V 3.0.2509

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Problem Description:

When "Allow users to login without a password" is enabled, can the password field be removed from the login page? I know the admin needs a password, but v2 handle this well by asking for a password only after trying to login as the admin user.

**Comment by tidusjar** [comment]
A lot of people didn't like that functionality on V2 that's why I removed it... I'll leave this here for now to see if anyone else wants this.

**Comment by Neaox** [comment]
I didn't like it due to the fact that it asked for the username and password separately, despite the fact that a password was required for all users.

I think @basmith7 idea of hiding the password field when `Allow users to login without a password` is enabled, then only asking for a password if the admin username is entered, is a good idea.

**Comment by tylerforesthauser** [comment]
+1 for this

**Comment by goldenpipes** [comment]
i just make everyone use their password :)

people really don't want to use a password? or they don't know it?

**Comment by antoinesylvia** [comment]
+1 for this.

**Comment by tidusjar** [comment]
Done!
