### ISSUE TITLE
Cannot run as upstart service (install wiki missing a step?)

### ISSUE THREAD

**Issue by keldian** [tidusjar/Ombi#1824]
#### Ombi build Version:

V 3.0.2534

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Media Server Version:

1.10.1.4602

#### Operating System:

Ubuntu 14.04.4 LTS (GNU/Linux 3.14.32-xxxx-grs-ipv6-64 x86_64)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

Irrelevant to issue

#### Problem Description:

When following the install instructions @ https://github.com/tidusjar/Ombi/wiki/Installation
Running `sudo service ombi start` after following the previous steps returns _ombi: unrecognized service_

#### Reproduction Steps:

Started over from scratch. Same result.

**Comment by keldian** [comment]
Ok I figured it out.

I started over and named the dir `/opt/ombi` rather than `/opt/Ombi`
I also ran `sudo chmod +x /etc/init.d/ombi` before the `sudo service ombi start` step

**Comment by jasonlyle88** [comment]
@keldian, thanks for catching those things. I know this is closed, but for future people that might find this tread, I just wanted to say I updated the wiki based on the above information.
* The init.d script now sets the service's path to `/opt/Ombi` instead of `/opt/ombi`.
* Added the `chmod` step after the user saves the init.d script
