### ISSUE TITLE
[LC] Issues Details Page needs some artwork

### ISSUE THREAD

**Issue by leram84** [tidusjar/Ombi#1907]
Can you throw the bg and poster in that page? Don't care where or how u style it cause im gonna change it anyway, but i need the content there. If you dont feel like setting it up, feel free to `display: none` on the base css.

**Comment by anojht** [comment]
@leram84 BG and Poster are ready. Please style the page as its currently looking standard. 
@tidusjar Just realized this, remember how providerid field was not being set properly prior to my commit so the issues created prior do not have a value for providerid so they will not load the images. Issues created after the new update will work just fine since I fixed the providerid field being set properly on issue creation.

**Comment by leram84** [comment]
Awesome @anojht !! Think you might wanna take a stab at some of the other [LC] issues? Its not really practical for me to release anything till they are all done, since each change to the ui generally means i have to go back and re-write most of this house of cards lol. But great job either way! Much appreciated :)

**Comment by anojht** [comment]
@leram84 I will see if I can knock out the other LC issues over the next few days, if there are any specific things you want please update the issues as it will be easier for me to implement those as I work on them!

**Comment by leram84** [comment]
oh man... caaaaannnn doooo lol. Nothing will change, but im sure some new things have come up since there have been a lot of additions since i made those issues. You on discord? Feel free to jump in the layercake room in ombi or organizr's server, or just pm me if u want/need anything, but ill go through and make sure there isn't anything else that needs to be added to the existing issues.

**Comment by anojht** [comment]
I am in the Ombi discord my discord name is MrGoldenPhoenix. Sounds good!
