### ISSUE TITLE
Removed requests show as "requested" when trying to re-add

### ISSUE THREAD

**Issue by tsborland** [tidusjar/Ombi#1927]
#### Ombi build Version:

V 3.0.2772

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Fedora 26

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

N/A

#### Problem 

After deleting a request, I cannot re-request via search.

#### Reproduction Steps:

Search for a movie/tv show
Add a request
Remove the request
Search for the same movie/tv show
It appears as "requested"

A restart did not resolve this.

**Comment by tidusjar** [comment]
Is it in radarr now?

**Comment by tsborland** [comment]
The movie is in radarr and downloaded, but still shows as "requested" in search.

**Comment by tsborland** [comment]
Looks to be resolved in 3.0.2822

**Comment by Hummuna** [comment]
I was able to reproduce this error in build 3.0.4817

Build: 3.0.4817
OS: Server 2012 R2

I was able to somehow reproduce this error for a single movie. I added the movie it didn't send to Radarr (new config / learning) so I removed the request. The movie in search says requested but it isn't in the Requested section. 

I wish there was a feature to / button to attempt to resend request to Radarr rather than removing  and re-adding. 

All other movies are I am able to request and remove without issue and Radarr is now properly configured.
