### ISSUE TITLE
[Feature Request] "Upcoming Series" list

### ISSUE THREAD

**Issue by EddiYo** [tidusjar/Ombi#211]
One thing I am missing from the request bit for the TV show section is a "Upcoming Series" list. I am not sure where to pull that from to be fair.

Did try to find something on thetvdb that might suffice, but no luck. But would be a neat feature so that people didnt have to go for other sites to find new and interesting series. Maybe even some sort of "tag" function if any of the tv sites have that active?

//Ed

**Comment by tidusjar** [comment]
I'd like to do this but I'm not sure where to get the information from. We need a Api
Provider that has this.

**Comment by csy7550** [comment]
Tvmaze has a REST API for this

**Comment by tidusjar** [comment]
Does it?! I'm using TVMaze currently. So if they have a endpoint that does this then excellent.

**Comment by Drewster727** [comment]
@csy7550 I'm not seeing it. Got a link?

**Comment by csy7550** [comment]
Maybe I misunderstood, but couldn't this be solved by using the scheduel api? 

http://www.tvmaze.com/api

**Comment by Drewster727** [comment]
That gives a list of episodes and when they air. It doesn't necessarily indicate when a "New" show is airing. I think what we want to add is an "Upcoming New Shows" option, where we list out *new* shows airing in the near future.

**Comment by tidusjar** [comment]
Looks like this might be possible with TVMaze, using the Show index. We would need to setup a schedule to get all of the TVMaze data into our local db and then filter them on the 'weight'.

There is a lot to think about if we go that way, since we need to make sure we refresh the data every time and ensure there is nothing out of date (TVMaze data is cached for 24 hours).  If we do go down this route then we may want to change the searching to use the local db instead of the API for faster results.

What's your opinion on this @Drewster727 ?

**Comment by tidusjar** [comment]
Just re-looking at the Api, nothing has changed yet. We can either store in the DB or in memory. Storing in memory might be an advantage since we will not have to manage the state of it as much (Similar to what we do with the CPCacher/SonarrCacher).
