### ISSUE TITLE
Ubuntu Package - Each time it updates the service file is overwritten

### ISSUE THREAD

**Issue by Ackis** [tidusjar/Ombi#2195]
#### Ombi build Version:

 3.0.3230-develop

#### Operating System:

Ubuntu 16.04

#### Problem Description:

I run Ombi on a different port than default (in my case 9999).  As a result, I need to run ombi with the --host command so I can specify the port - this entails editing the ombi.service file.  Whenever I upgrade via the package manager it overwrites the ombi.service file.

#### Reproduction Steps:

`apt-get update && apt-get upgrade ` :)

**Comment by tidusjar** [comment]
I don't manage this package.

**Comment by Ackis** [comment]
I thought it was official with it being posted here. :) Sorry

https://github.com/tidusjar/Ombi/wiki/Installation#linux-systems

**Comment by tidusjar** [comment]
That's fine, the wiki is community driven!

> This repo is maintained by @louis-lau. Go bug him on discord if you have problems specifically with the repo.

**Comment by louis-lau** [comment]
@Ackis Didn't think about that. I'll see what I can do!

**Comment by louis-lau** [comment]
@Ackis looks like it's a feature, not a bug! ;)

You're not supposed to edit service files directly when they're installed by a package. See https://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services

**Comment by jasonlyle88** [comment]
@louis-lau Basedon the askubunut question you linked, what about including

```
[Service]
EnvironmentFile=/etc/default/ombi
```

In the service file and using defaults for the variable if 1) /etc/default/ombi does not exist or 2) /etc/default/ombi does exist but does not set a particular variable. This would allow ombi users to easily customize the service without needing to understand how systemd works. They could just create their /etc/default/ombi file and override any variables that are used in the file (which could be easily documented).

The only issue I see with this is if someone wants to use something other than ombi as their service name. The environment file at /etc/default/ should match the service name. But, really, if they are changing their service name, I am guessing we can just write it off as an advanced configuration and they can just override the systemd service as mentioned in the previous askubuntu link.

All that being said, it can also just be documented how to override the systemd service as well. Both are viable options. The /etc/default/ files just feels a little more familiar to config files from SysV init systems and thus may be easier to grasp.

Thoughts?

**Comment by Ackis** [comment]
@louis-lau @jasonlyle88 I don't consider myself to be a novice linux user, but I know I'm not advanced. 
 Maybe I just know enough to be dangerous? ;)  Anyways, when I was first looking into this, I checked to see if there was one of the following config files:

- /etc/default/ombi
- /etc/ombi/ombi
- /etc/ombi

I didn't find one so I just went with manually editing the ombi.service file.  Just wanted to give you my thought process.  And I guess this is a long winded way of saying I agree with @jasonlyle88  :)

**Comment by louis-lau** [comment]
I didn't know either before I looked it up! :)
Maybe we can just add the process to the wiki? I'd add a different page because the installation page is getting very long.

Btw, what @jasonlyle88 said about the EnvironmentFile won't work. Because we don't accept the host name and port as an environment variable but as an argument to the command. Correct me if I'm wrong.

**Comment by jasonlyle88** [comment]
@louis-lau I'm guessing you are correct, the way the service file is currently working it does not work. I say that I'm guessing because I don't have a system that currently has your systemd service file, so I don't know what it looks like. You would have to update the service file to use variables for the call. Consider below purely an example:

#### /etc/default/ombi
```
ombiPort=9999
```

#### Ombi SystemD Service file proposed changes
```
...
[Service]
Environment=ombiHost=foo
Environment=ombiPort=bar
EnvironmentFile=/etc/default/ombi
...
ExecStart=/opt/Ombi/ombi --host $ombiHost --port $ombiPort
...
```

In theory, the variables should be set by the `Environment=[VAR_NAME]=[VAR_VALUE]` lines, and then get overridden if any of the same variables exist in the `EnvironmentFile`. Then the variables can be used in the ExecStart call.

I have not tested this, but it seems like it should work. Usually I would be happy to jump in and test this all out, but I unfortunately don't have the time/system to do this right now.

Other things to consider are if these truly set environment variables or just locally scoped variables for the duration the the service call. I assume not polluting the global environment space would be preferable.

**Comment by louis-lau** [comment]
Currently the service file is the same as the one on the wiki. I guess that would work.

I *guess* it would be easier for end users, but it's custom. Isn't it nice just to do it the way systemd intended?

**Comment by jasonlyle88** [comment]
@louis-lau Oops, I just edited my answer to include a section on what you just mentioned!

**Comment by nemchik** [comment]
To me it makes sense to do something more like this:
```
...
[Service]
EnvironmentFile=/etc/default/ombi
EnvironmentFile=/opt/Ombi/env
...
ExecStart=/opt/Ombi/ombi --host $ombiHost --port $ombiPort
...
```
or
```
...
[Service]
EnvironmentFile=/opt/Ombi/env.defaults
EnvironmentFile=/opt/Ombi/env.custom
...
ExecStart=/opt/Ombi/ombi --host $ombiHost --port $ombiPort
...
```

The default file in both cases above would be used to store the defaults set by the package, and would be expected to be overwritten with package upgrades. the second line (custom) would be where the user can change their preferences. In either case I think the user editable preferences should be kept with the ombi installation in `/opt` because this puts it in a very obvious place for the user OR in `~/.config/ombi.env` or something but `~` may be a little harder to accommodate.
