### ISSUE TITLE
Request limit based on number of shows, not episodes

### ISSUE THREAD

**Issue by ajhong2** [tidusjar/Ombi#2305]
#### Ombi build Version:

V 3.0.3368

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

N/A

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

I remember that in v2 that you could limit requests of a user based on the number of total tv shows and not episodes. Is there a way to bring that back and have it as a separate option? (For example. A weekly limit of 3 total shows without consideration of number of episodes)

#### Reproduction Steps:

N/A

**Comment by tidusjar** [comment]
No that's not possible currently. 

Plus episodes is a better fit in most cases.

**Comment by Kazz3r24** [comment]
I don't see how limiting by episodes is a better fit for TV shows... Not every show has the same number of episodes per season - I've already run into issues where users were only able to request 1.5 seasons due to the episode limit. Not to mention, if I'm getting a show - I'm aiming for the whole thing regardless (OCD) and Anime completely kills this as well. 3 years later people are still looking for this.

Love the application, but you should really consider rethinking this.
