### ISSUE TITLE
Reporting an Issue Missing (Year) Variable

### ISSUE THREAD

**Issue by gold007eye** [tidusjar/Ombi#2484]
#### Ombi build Version:
V 3.0.3587

#### Update Branch:
Master

#### Media Sever:
Plex

#### Operating System:
Windows 7

#### Problem Description:

When creating an issue for a Movie or TV show the (Date) variable at the end is not showing correctly.  Movies just shows as "(Undefined)"
TV Shows show as "(2011-04-17T00:00:00)"

#### Reproduction Steps:
Movie Issue:
*Also not that there is a missing space between the end of the movie title and the ( to start the year of the movie.
![image](https://user-images.githubusercontent.com/4365462/44816361-ae7b3b80-aba7-11e8-820d-edb172d2ca70.png)

TV Show Issue:
![image](https://user-images.githubusercontent.com/4365462/44816503-0ade5b00-aba8-11e8-96ef-99f740dee9fc.png)

**Comment by tidusjar** [comment]
Fixed in develop

**Comment by seanvree** [comment]
@tidusjar  - this not only happens when the year is defined, it happens also when only the `{Title}` is defined

Example:

```
Hello! The user ' {UserName} ' has reported a new issue for the title {Title}! </br> Issue: {IssueDescription}
```
Result:

![ombi_undefined_tag](https://user-images.githubusercontent.com/8906637/44943217-c5748600-ad7f-11e8-8575-582ce9cd6238.png)



Not sure if your push fixed that, but just wanted to make sure you knew. 

Thanks brother, appricate you!
