### ISSUE TITLE
Music Artists Searching

### ISSUE THREAD

**Issue by Haywood78** [tidusjar/Ombi#2508]
I've noticed when searching for and artist that sometimes an artist ex: AC/DC is not found. Other artists 
ex: Pink Floyd when I click on view albums it tries to load but times out and never displays any albums. Overall the music request feature is working pretty well. Once the api command to start searching for requested albums is complete, should be a pretty solid feature. Far better than headphones ever was in my opinion.

**Comment by tidusjar** [comment]
Hello, 

Thanks for raising the issue, but in the future please **do not** delete the issue template.
It contains a lot of information that I require to investigate the issue.

> I click on view albums it tries to load but times out and never displays any albums.  
This is due to the way I have to get the albums, I have an open issue on Lidarr about this so I can improve it.

> Api command to start searching
This is in develop. But I cannot tell what version you are due to you deleted the template.

**Comment by Haywood78** [comment]
My bad. I will remember that. Thanks for the heads up.

**Comment by Haywood78** [comment]
I am currently on version .3712
