### ISSUE TITLE
Add `forwardUrl` parameter to return user to Ombi after Plex Auth

### ISSUE THREAD

**Issue by duncanbeevers** [tidusjar/Ombi#2548]
The Plex Auth App can return the user to their Ombi install after authentication by including a `forwardUrl` parameter.

Additionally, the `pinID` parameter is not necessary, and potentially harmful, and should be removed.

**Comment by tidusjar** [comment]
Hi @duncanbeevers 

I'm not sure which version you are since the template is not filled in.

But recently I changed the way we authenticate with Plex, we no longer use the `forwardUrl` as we are opening the Plex Website in a popup to authenticate.

Thanks for the information about the `pinID` i've now removed this in the develop branch and will go live with the next release.

**Comment by duncanbeevers** [comment]
Thanks. I'm just getting Ombi, running 3.0.3795 via this Docker image https://hub.docker.com/r/linuxserver/ombi/

**Comment by tidusjar** [comment]
Ok, well when the next release build goes out that image will get rebuilt automatically and the changes will be in that.

Thanks
