### ISSUE TITLE
Ombi install compromised/used as backdoor

### ISSUE THREAD

**Issue by AthlonII240** [tidusjar/Ombi#2559]
#### Ombi build Version:

V 3.0

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

Windows Server 2012 R2

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

Last night my Ombi instance on my server at home was updated, and this update either included trojans and a backdoor, or was used as an attack vector to compromise my server. Ombi was updated on 10/3 8:03PM EST, which replaced my existing copy of Python 2.7 a few minutes after that which was used to further infect my server. Ombi logs of course showed nothing beyond "1 scheduled job(s) enqueued."

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Ok.

Here's a few questions

1. How do you update Ombi?
2. How do you run Ombi?
3. What user do you run Ombi under

**Comment by AthlonII240** [comment]
1. I update Ombi through the Update portion within the Admin configuration page in Ombi itself. 
2. I run Ombi as a service using NSSM
3. Ombi runs as a user that has administrative access to the server it resides on. Not "Administrator" but a separate user entirely.

**Comment by tidusjar** [comment]
There is a bug in Ombi currently that Automatic updates will not work with Ombi running as a windows service. It will try but fail because Ombi does not know how to stop the windows service yet.

What is the version of ombi you are running?

**Comment by AthlonII240** [comment]
I'm not 100% sure, as I can no longer open my Ombi instance because Malwarebytes now identifies it as infected. I ran the update manually last night, as I saw there was an update available upon logging into my Ombi instance. After it updated, the Ombi web page seemed to come back fine and I didn't investigate further. I tried to log in this morning to it, found the web page unresponsive, and that is what prompted me to open this can of worms and discover my server was now compromised.

**Comment by tidusjar** [comment]
I am very confident that Ombi is not the cause of this since it can't actually update anything on your server because the updater doesn't work with Windows Services.

The only think it would have done is download the verified update zip from here: https://github.com/tidusjar/Ombi/releases

It sounds like something else has affected your server.

**Comment by AthlonII240** [comment]
I thought that too that maybe something else compromised the server, but the only change done last night to it was installing the Ombi update. 

At this point, there's not much either of us can do about this. My only suggestion is pouring over the Ombi codebase and ensuring that potential attack vectors found within are minimal, if present at all.

**Comment by tidusjar** [comment]
I can assure you that in your scenario nothing happens.

Here is the process:

1. Update Started
2. Check Github Changelog to see if there is a new update compared to the installed version.
3. If true then download the `.zip` from the releases section on Github
4. Extract the `.zip` file to a folder called `TempUpdate`
5. Launch the `Ombi.Updater.exe` 
6. The `Ombi.Updater` process will try and kill the `Ombi.exe` process
7. Error because it couldn't kill the process (Windows Services would have restarted it)
8. `Ombi.Updater` process would have exited
9. `Ombi.exe` would still be running with no changes.
