### ISSUE TITLE
The Return (2018) not showing up

### ISSUE THREAD

**Issue by matijaerceg** [tidusjar/Ombi#2683]
#### Ombi build Version:

V 3.0.3988

#### Update Branch:

master

#### Media Sever:

Plex

#### Operating System:

Linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```


```

#### Problem Description:

The movie The Return (2018) is not showing up, but it exists on TMDB

#### Reproduction Steps:

1 - go to search page, and do a search for The Return

Expected behavour: This movie shows up https://www.themoviedb.org/movie/498416-the-return?language=en-US

What happens instead: the movie does not show up in the search results

**Comment by tidusjar** [comment]
This is due to the way TheMovieDb is returning that movie in the result.

Currently we limit the rest to 10 results, this is due to us not wanting to overload the API. I increased it to 15 on my local environment to see what happens and it still doesn't appear.

It seems when searching for `The Return` there are 635 results on TheMovieDb.... The thing I need to do is add paging to the movie search.

**Comment by tidusjar** [comment]
Added an option to provide a year to search for in develop
