### ISSUE TITLE
Requesting single season, sonarr monitors all

### ISSUE THREAD

**Issue by velcropaste** [tidusjar/Ombi#2801]
Bug description: Requesting and approving one season of tv-show results in sonarr monitoring all seasons. 

Reproducing: Tried approving through the Android app and web interface, same result. Tried requesting "last season" and and "first season", same result. 

Expected behavior: only the requested and approved seasons be added to sonarr. 

OS: win sever 2016

Ombi Version 3.0.4119
Media Server: Plex 
Sonarr Version 2.0.0.5301

The correct seasons appear for me to approve, ie just just the first or last, and shows up correctly in the list of requests made after approval.

**Comment by tidusjar** [comment]
Is this for new series in sonarr or do they already exist in sonarr?

**Comment by velcropaste** [comment]
> Is this for new series in sonarr or do they already exist in sonarr?

I've only tested on series that doesn't already exist in sonarr. Just tried adding a series in monitored in sonarr, and then request first season in ombi, and it was correctly monitored in sonarr!

**Comment by tidusjar** [comment]
OK thanks for the information!

**Comment by tidusjar** [comment]
I cannot seem to reproduce this issue:
https://imgur.com/eZsVlQf.gifv

**Comment by velcropaste** [comment]
Just tried with auto-approve, and it seems to work for me aswell. Try with
manual approve? That's what I'm using when the problem occurs.

Den ons 13 feb. 2019 22:54 skrev Jamie <notifications@github.com>:

**Comment by tidusjar** [comment]
Ok I'll investigate

**Comment by ptizzl** [comment]
I have this same issue. It doesn't happen when I have auto approve and do it through my admin but if someone that's not an admin requests even a single episode, it will monitor the entire series, but it still won't search for any episodes.

**Comment by ptizzl** [comment]
I can add a little more detail. This only happens when the admin has to approve the request. For example: I have a user with request only privileges. That user requests an episode. Admin approves request, it adds the entire series (every episode, every season) to Sonarr as monitored, but it does not search anything. This is for new series not in Sonarr. If there is a season in Sonarr but missing an episode, the normal request procedure works. 

If I have another user with auto approval turned on, everything works as expected.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
