### ISSUE TITLE
Nitpicking about capitalizing the words “TV show” and “Movie”

### ISSUE THREAD

**Issue by gdob** [tidusjar/Ombi#2820]
Hello,

I know to many of you this isn’t an issue, but I really don’t like it when I see words not capitalized properly. For example the email I’m getting contains the following subject: _New **Tv show** request for Game of Thrones_. 

It would be nice if we could change `Tv show` to `TV show` and `Movies` to `movies` where applicable, so the quoted line above becomes this and looks better to the end user: _New **TV show** request for Game of Thrones_.

Or, let’s say the e-mail message content: _The user John has requested the **Movie** “Die Hard”_ becomes _The user John has requested the **movie** “Die Hard”._ 

And so on. A change would be enough only where the end user sees a notification, an email message, a Discord message, etc. I don’t know how to code and I don’t understand your code on Ombi, but I’m just guessing the variable `{Type}` needs some tweaking.

Sorry, I’m a stickler for things like these, so please don’t mind me for being too “pedantic.” It’s just a suggestion. I think Ombi is a great piece of software and this can make it look more professional. Thank you.

**Comment by goldenpipes** [comment]
shouldn't be too hard to rectify!  Thanks!

**Comment by slopra** [comment]
I'm of the same picky mindset and 100% agree with this. I may just be ignorant, but I was initially thinking if it would be possible to just use the variable {type} 'movie' instead of {Type} 'Movie' but I see where this wouldn't work for the current output 'Tv show'

I would bet that the users who don't care, being that they don't care... would be ok with 'TV show' and 'movie'
And of the users that do care, I can't imagine any of them preferring the current 'Tv show' and 'Movie'
