### ISSUE TITLE
Sonarr/Radarr Webhook Integration

### ISSUE THREAD

**Issue by McGriddle** [tidusjar/Ombi#2840]
Instead of polling sonarr and radarr, could the webhook features of both be used to update ombi?

**Comment by tidusjar** [comment]
Thanks for the suggestion!

But... I'm currently handling feature requests on Feathub over here -> http://feathub.com/tidusjar/Ombi

If you could please check if the feature has already been requested, if it's already on there then 👍, If it hasn't been requested then please feel free to suggest a new feature on there.

Thanks

**Comment by tidusjar** [comment]
This is a good idea, I didn't know this could be done

**Comment by tidusjar** [comment]
I'd need the following to be able to achieve this:

https://github.com/Radarr/Radarr/issues/3375
https://github.com/Sonarr/Sonarr/issues/2965

Since currently the Webhooks provided would only be able to provide Ombi with information about if it has been downloaded etc which is not really relevant to Ombi.
