### ISSUE TITLE
Gigantic -json.log file with Docker

### ISSUE THREAD

**Issue by lastb0isct** [tidusjar/Ombi#3067]
**Describe the bug**
My Docker system came to a halt and wasn't able to do anything on it because there was a -json.log file that was over 30Gb!  Not sure what could be causing this...

**To Reproduce**
Essentially let Ombi run and the log filled up.

**Expected behavior**
Have logs be cleaned up?

**Desktop (please complete the following information):**
 - OS: RHEL7 with Docker

**Ombi Version (please complete the following information):**
 - Version 3.0.4669
- Media Server : Plex

**Comment by lastb0isct** [comment]
Might have fixed this with the following environment variables...will report back if it is not fixed.

      - Logging:LogLevel:Default=Warning
      - Logging:LogLevel:System=Warning

**Comment by tidusjar** [comment]
What is the full file name? Because Ombi doesn't create a `-json.log` file?

**Comment by apetresc** [comment]
I'm also experiencing this - Ombi (at least, the LinuxServer.io container for Ombi) generated about 40GB of logs in a week, even though there are only about 2 users on the instance.

To answer @tidusjar's question, it happens to both the Docker-generated logfile coming from stdout, and (to a lesser extent, because they are rotated) the `.txt` files in Ombi's own `Logs` directory. The logs seem to just be filled with massive JSON metadata about every single item in the Lidarr/Sonarr/etc library every minute or so.

A way to configure the log verbosity way _way_ down would be awesome.

**Comment by tidusjar** [comment]
What version are you running>?

**Comment by apetresc** [comment]
`3.0.4654`. I can try upgrading to 4659!

**Comment by tidusjar** [comment]
Yeah on a specific older version the debugging was set to low, that was an accident on my behalf.

**Comment by lastb0isct** [comment]
I'm on 3.0.4669 and this was happening -- On Docker specifically. So maybe it's still by default in later versions of docker as well?

**Comment by tidusjar** [comment]
That's strange because currently the LogLevels are set to Information by default now
https://github.com/tidusjar/Ombi/blob/master/src/Ombi/appsettings.json
