### ISSUE TITLE
OMBI allowing request of already available movies

### ISSUE THREAD

**Issue by Egleu** [tidusjar/Ombi#3127]
**Describe the bug**
Ombi is allowing users to request movies that are already available in Plex.
Plex has connection to ombi, it even notifies when new movies are available. I've tried running a full sync several times as well.

**Desktop (please complete the following information):**
 - OS: [Openmediavault]

**Ombi Version (please complete the following information):**
 - Version [3.0.4680]
- Media Server [Plex]

**Additional context**

**Comment by tidusjar** [comment]
Can you include log files after a Plex Sync has run?

The issue doesn't really give me much to go on.

**Comment by JimboMonkey1234** [comment]
I'm guessing this is intentional for unmonitored movies, see #3010. 

@tidusjar, why is it expected to be able to request unmonitored movies? This was surprising for me (and at least one other person, see this [reddit](https://www.reddit.com/r/Ombi/comments/cad4gt/error_tmdbid_is_not_0_for_movie/?st=k09ym7cw&sh=f4371b50) thread).

Can I suggest making this behavior optional? Even if you keep it this way though, I think the logging can be improved. Right now the [code](https://github.com/tidusjar/Ombi/blob/3b46f14c08b575c6bf90dbf06357ddd7914123ca/src/Ombi.Schedule/Jobs/Radarr/RadarrSync.cs#L59) looks like:

```c#
if (m.tmdbId > 0 && m.monitored)
{
    movieIds.Add(new RadarrCache
    {
        TheMovieDbId = m.tmdbId,
        HasFile = m.hasFile
    });
}
else
{
   Logger.LogError("TMDBId is not > 0 for movie {0}", m.title);
}
````

Which means that error gets logged even for unmonitored movies, which made me think Radarr had a bug.

**Comment by tidusjar** [comment]
Check develop, it was fixed a few weeks back

**Comment by JimboMonkey1234** [comment]
Nice, [that](https://github.com/tidusjar/Ombi/commit/f772a60bc34932341ea061a07951c3d09423c58f) fixes the logging. Still, it'd be nice to prevent requests of unmonitored movies. Should I make a FeatHub request or is there something else I'm missing here?

**Comment by JimboMonkey1234** [comment]
Not sure I understand what you mean by:
> Because it's unmonitored, if we showed as requested, that request would never be fulfilled.

I use unmonitored to mean "I have this movie and I'm happy with the quality", so why would I want someone to be able to request it?
