### ISSUE TITLE
Link previews showing incorrect data

### ISSUE THREAD

**Issue by robbiemcleod56** [tidusjar/Ombi#3397]
**Describe the bug**
I have set up Ombi completely since yesterday, linked Plex, Sonarr and Radarr, and it seems to function just as expected, except for one thing. When I send a link to a friend on Facebook or Discord (or even use https://guteurls.de/ to generate a preview) to access Ombi, the link preview doesn't show up correctly, only a single quote and the first word appear. The application name is three words long, and I suspect this might be the problem. 

**To Reproduce**
1. Log into Ombi as an admin.
2. Go to settings> Configuration> Customization and set the Application name to "three word test" or anything else with three words (without quotes.)
3. Use any link previewer like the ones mentioned above.
4. Notice the title is not as expected. In the case of this example, the title would read: "three

**Expected behavior**
The title in the link preview should match the application name. 

**Screenshots**
Screenshot of the link preview of my own setup on gute-urls (same result everywhere): 
![image](https://user-images.githubusercontent.com/7958152/74640523-b0d7a980-513d-11ea-8e7d-5ac9f613fca3.png) 

**Desktop (please complete the following information):**
 - OS: Windows 10 1809

**Ombi Version (please complete the following information):**
 - 3.0.4892 master branch
- Plex

**Comment by robbiemcleod56** [comment]
It is not stale, the issue still persists.

**Comment by robbiemcleod56** [comment]
Thanks, stale bot. Lol.

**Comment by joemama155** [comment]
+1 for this, the issue is the quote being used is wrong.

from view source:
![image](https://user-images.githubusercontent.com/17011324/82839548-b7449280-9e9d-11ea-9323-4b171d2494a2.png)

from inspector:
![image](https://user-images.githubusercontent.com/17011324/82839275-d8f14a00-9e9c-11ea-9fe6-600309328a8e.png)


look closely at the quotes surrounding og:title and the quotes surrounding Ombi.
its the same for og:site_name

the browser tries to compensate for this and tries to fix it on its own and just surround it in the proper quotes which is great until you try and name your app something with multiple words then you get this:

![image](https://user-images.githubusercontent.com/17011324/82839957-0a6b1500-9e9f-11ea-8a58-fa2177e7cc15.png)

also the og:image seems to point to a link that cant be accessed thru the reverse proxy and it does not get its value from where we customize the logo.

**Comment by robbiemcleod56** [comment]
Not stale. Again.

**Comment by hmnd** [comment]
@robbiemcleod56 This was fixed in #3598.
