### ISSUE TITLE
v4 - Sorting Requests by Title

### ISSUE THREAD

**Issue by MikeFalcor** [tidusjar/Ombi#3682]
**Describe the bug**
When you try to sort requests by title, it either sorts Z to A or by Request Date.

**To Reproduce**
1. Go to Requests (assuming you have at least a few...)
2. Click on Title to sort lexicographically - It will only do Z to A or by Request Date

**Expected behavior**
Sorting A to Z or Z to A should happen when you click on Title. It should only sort by Request Date if you click on THAT header.

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 2004

**Ombi Version (please complete the following information):**
 - Version: 4.0.411
 - Media Server: Plex

**Additional context**
N/A

**Comment by MikeFalcor** [comment]
Still doing it on the latest update.

**Comment by gold007eye** [comment]
Looks like this issue is back in the latest version (4.0.779.0).
OS: Win10 Pro x64

When I Sort by Title First click puts Z-A, but second click is not changing order to A-Z.

Sort Order Examples by Title:
![image](https://user-images.githubusercontent.com/4365462/102732614-ce971180-4300-11eb-8866-ad1eff1831de.png)

![image](https://user-images.githubusercontent.com/4365462/102732644-e2427800-4300-11eb-87a2-487c601324c2.png)
