### ISSUE TITLE
Ombi requests are not being added to Sonarr or Radarr

### ISSUE THREAD

**Issue by Pixxel123** [tidusjar/Ombi#3855]
**Describe the bug**
Ombi does not add requests to Sonarr or Radarr.

**To Reproduce**
1. Press Request button.
2. Check Request screen.
3. Content status changes to Processing Request but this does not seem to be added to either Sonarr or Radarr.

**Expected behavior**
I expect the requested content to show up on Sonarr or Radarr.

**Logs (Logs directory where Ombi is located)**
Here is a pastebin of the log: https://pastebin.com/QPpvPPG2.

**Desktop (please complete the following information):**
 - OS: Linux (Seedbox)

**Ombi Version (please complete the following information):**
 - Version: 3.0.5223
- Media Server: Plex
- Database Type: SQLite

**Things I've tried:**

- The checkbox for both Radarr and Sonarr is set to ENABLED.
- Test Connectivity on both shows as successful.
- My main user has these permissions: AutoApproveMovie,m RequestTv, RequestMovie, AutoApproveTv, Admin
- Tried setting up a test user with the same permissions EXCEPT Admin.

**Comment by tidusjar** [comment]
I'm pretty sure these issues are fixed in v4

**Comment by Pixxel123** [comment]
Hi, I've now installed Ombi 4.0.641.0, but this still seems to persist. This time around though, I can't seem to find the logs for Ombi V4, have they moved? I've tried checking in `.ombi/Logs/` but it seems to be empty now.

**Comment by daymanbpi** [comment]
Also having this exact issue issue. 
Ombi - 4.0.551.0
Radarr - 3.0.0.4071
Sonarr - 3.0.4.999

**Comment by tidusjar** [comment]
Have you enabled it in the settings? People usually miss that

**Comment by daymanbpi** [comment]
> Have you enabled it in the settings? People usually miss that

Sorry for the blunt response. But Enabled what setting? 
I have combed over all the settings i think. Im not sure what you mean.

**Comment by EGeekBMe** [comment]
I have been having this same issue...

**Describe the bug:**
Requests made via OMBI are not being added to SONARR v4 and are hanging at "Processing Request" and it never clears are gets added to SONARR.

Requests for movies made via OMBI get added to RADARR v4 just fine and without any kind of issue.

**To Reproduce**
Request a TV Show via OMBI
Request just sits with "Processing Request" status

**Expected Behavior**
I expect the requested content to show up on SONARR.

**Logs (Logs directory where Ombi is located)**
Here is a pastebin of the log: https://gist.github.com/EGeekBMe/e39ea1f17feeb29d5dfae5f481b95847

**Desktop (please complete the following information):**
OS: Linux 5.4.31-gentoo-whatbox (seedbox)

**Ombi Version (please complete the following information):**
Version: 4.0.1035.0
Media Server: Plex
Database Type: SQLite

**Things I've tried:**
- The checkbox for Sonarr is set to ENABLED.
- Test Connectivity on both shows as successful.
- Base User has Auto Approve permissions for both TV and MOVIE (Movies work fine)
- Tried as admin user and same result.
- C&P the SONARR API
- Confirmed port
- No Base URL in use but tried with just a / which passes connectivity test.
- Also tried with base url of /sonarr and fails connectivity test.

**Comment by joker3287** [comment]
I have the most up to date Ombi when I do the Plex watchlist it works perfectly with Radarr however every time I try to do a TV show I get an error that it couldn't be added. Where should I start to try a troubleshoot this?
