### ISSUE TITLE
Version 4.0.698 release or newer: System.IO.FileLoadException: 0x80131621

### ISSUE THREAD

**Issue by 5drH64gDnDJb** [tidusjar/Ombi#3884]
**Describe the bug**
Upgrading from version 4.0.681 to anything newer, I get an error on startup. I am using Mysql

**Logs (Logs directory where Ombi is located)**
[ombi log.txt](https://github.com/tidusjar/Ombi/files/5587064/ombi.log.txt)

**Comment by escservices** [comment]
@5drH64gDnDJb This happened to me, you can't overwrite the files in your ombi directory, you'll need to backup your database.json file and delete everything in the folder, then extract the new update into the folder and put your database.json file back.  That's how I've been doing the upgrades since 4.0.681 and it has worked fine since.

**Comment by 5drH64gDnDJb** [comment]
> 
> 
> @5drH64gDnDJb This happened to me, you can't overwrite the files in your ombi directory, you'll need to backup your database.json file and delete everything in the folder, then extract the new update into the folder and put your database.json file back. That's how I've been doing the upgrades since 4.0.681 and it has worked fine since.

Ahhh i figured that might be the case, I was just being lazy lol, I'll do that tomorrow thanks.
