### ISSUE TITLE
Change default interface language

### ISSUE THREAD

**Issue by Ruvetuve** [tidusjar/Ombi#401]
Hi,

I'd like the feature in Admin panel of forcing the interface language. Users can still choose, but i want to set a different default language instead of English.

Ty.

**Comment by tidusjar** [comment]
Is this needed?
Because if the user's browser is setup correctly (e.g. the language is set) then the website should default to that language. If they change the language and then comeback to the site, it will stay in the language that they selected (Unless they clear their browsers cookies, since we store a cookie called "_culture", the cookie expiry date is a year IIRC).

**Comment by Ruvetuve** [comment]
It was default English for me.. and iam using Dutch settings in my browser (Chrome). Firefox indeed shows the correct language. If i can force this i never have to worry about it anymore :)

**Comment by tidusjar** [comment]
Ah ok, maybe that's a bug then. I can take a look into setting the default language.

**Comment by ElYoM** [comment]
I think it's a good idea. I have only french speaking users on my server and it will be more useful for me to force only French translation to be displayed to them (maybe hiding language selection menu when the choice is forced).

**Comment by SuperPotatoMen** [comment]
This is already possible in te 2.0 version :)
