### ISSUE TITLE
Enable User Notifications By Default

### ISSUE THREAD

**Issue by taytortots** [tidusjar/Ombi#433]
Couldn't think of a better title for this, so read on for an explanation.

Currently, users have to click the bell icon and opt-in for notifications about requests. It would be great if this option could be changed for all users from the admin side of things so that all users receive email notifications without having to opt-in.

**Comment by tidusjar** [comment]
This will take a bit of thinking.

What happens is when a user enables this we store that in the database against the users Plex Account.

So if you enable it we need to lookup all the Plex accounts and store a settings against it saying we want notifications. 
What happens when someone is added to your Plex account... There is no way without periodically checking to know.

**Comment by jdelvecchio** [comment]
Nice feature, I'd like to have that too!

**Comment by SuperPotatoMen** [comment]
@taytortots,

this feature is available in the upcoming release of 1.10.0

You can force the enable it for every user:
![image](https://cloud.githubusercontent.com/assets/2944704/20776582/bfbe1f34-b761-11e6-91af-f90b572888b5.png)

**Comment by enz1ey** [comment]
This option seems to be missing in version 2.2.1678

All my users have the "Request Added Notification" disabled by default in the "User Management" pane

**Comment by PotatoQuality** [comment]
The bell icon option is removed. Only admins can enable or disable it in the the User Management panel.
