### ISSUE TITLE
Set default language for titles

### ISSUE THREAD

**Issue by Jonn3y** [tidusjar/Ombi#460]
Hey and hello from Germany,

is it possible to set the default language for all the titles? 

Movie example: 
<img width="1084" alt="bildschirmfoto 2016-08-08 um 20 06 35" src="https://cloud.githubusercontent.com/assets/11927089/17490634/ffca2b94-5da3-11e6-88e4-694a1feeaf4c.png">
Im searching the german title: Das Beste kommt zum Schluss
and I get the english title: The Bucket List

Is it possible to show the german/(insert your language here) title?
URL for right german title would be:
 https: //www.themoviedb.org/movie/7350-the-bucket-list**?language=de-DE**

Best wishes!

**Comment by tidusjar** [comment]
Hey dude. I have got a similar request for this. Yes it can be done. Just need to check the API!

**Comment by Jonn3y** [comment]
Would be awesome to get it working :)

**Comment by nickiman** [comment]
Hi @tidusjar 
After start to use PlexRequests for a while for first time... what I´m missing from now was that @Jonn3y commented... just to add the possibility to get the information of the movies from themoviedb.com with different languages in order to show the title translated and the poster related:
https://www.themoviedb.org/movie/127585-x-men-days-of-future-past?language=es-ES

It happens also with the series section where we need introduce the name of the serie ONLY in English... if I search "Juego de Tronos" it doesn´t show anything but if I write "Game of Thrones" I can see the serie listed and, as you probably know thetvdb.com has also that feature to search and get the info in different languages:
http://thetvdb.com/?tab=series&id=263365&lid=16

Do you think that will be feasible also to implement this feature in both sections?

Keep in touch.

**Comment by dingsbums** [comment]
It would be great if we could set a default language for the interface and of course for the request titles.

thanks

**Comment by tobsen987** [comment]
Any news on this?

I think to get info from tmdb in another language you have to add &language=de-DE (e.g. for german) to the API call. (https://developers.themoviedb.org/3/movies)

Could be connected to selected interface language in ombi?

**Comment by viruz82** [comment]
+1

**Comment by PotatoQuality** [comment]
@viruz82 ???

**Comment by gelsas** [comment]
Any update on this?

**Comment by rix1337** [comment]
This would indeed be great. Right now, we have to wrap both tmdb and tvdb when wrapping the ombi api in localized apps to get correct titles.
