### ISSUE TITLE
[BUG] PR search does not return correct results after adding new items to Plex

### ISSUE THREAD

**Issue by secdeath** [tidusjar/Ombi#638]
#### Applicable Logs (from `/logs/` directory or the Admin page):

See attached for app logs

[2016-11-01.txt](https://github.com/tidusjar/PlexRequests.Net/files/566937/2016-11-01.txt)
[2016-11-02.txt](https://github.com/tidusjar/PlexRequests.Net/files/566938/2016-11-02.txt)

#### Reproduction Steps:

After requesting new items from PR and after Couchpotato/Sickrage has them downloaded; PR searches returns results consistent with an empty Plex DB. This means that all search results in PR show as requestable rather than some being already in the Plex DB. After at least an hour or two searches eventually show correct results.

Edit: After messing with this more to try to consistently reproduce; It looks as if this issue occurs when adding a few new requests to PR. I'm not sure if the PR DB somehow re-initializes or something in some cases?

**Comment by secdeath** [comment]
I wasn't sure if this was actually related to https://github.com/tidusjar/PlexRequests.Net/issues/632 so I opened a new issue..

**Comment by tidusjar** [comment]
So there is a background job that scans the Plex library, by default this is every hour, so you will have to wait for this to run before you can see Plex Requests update to available. 

You can change this in the scheduled settings, it's the Plex Availability Checker.

**Comment by SuperPotatoMen** [comment]
@secdeath is the problem still there after the run of  Plex Availability Checker?

**Comment by secdeath** [comment]
i think you can close this. though i would like to see the db only re-populate what it doesn't have rather than the entire thing. Do you think you can do incremental DB updates rather than a completely new load of the entire DB?

**Comment by tidusjar** [comment]
We don't store them in the DB, every time Plex Requests starts up we store
the Plex, Sonarr, CP stuff into a in memory cache. Reason for this is that
the cache is a volatile cache and we can easily destroy it and recreate it.
This is a lot easier to manage rather than keeping track of what we have in
the cache and what we don't have.

It might be a good idea to store it in the database and just do updates,
but it can sometimes be difficult to manage e.g. Keep track of any
additions, deletions and modifications.
